input_width: 5
output_width: 5
n_head : 4
layers: 4


max_epochs: 50
gpus: 1
lr: 1e-3
batch_size: 1

# Are you training? Otherwise plot the result
train: True
checkpoint: null
rotations: 1 # 1 is x,y, 2 is x,y, x-y, x+y, greater includes additional rotations

defaults:
  - optimizer: lion
