

max_epochs: 50
lr: 1e-3
batch_size: 1024

# Are you training? Otherwise plot the result
train: True
checkpoint: null
accelerator: cuda

data:
  num_points: 100
  num_samples: 1000
  dims: ${network.input_size}


defaults:
  - optimizer: lion
  - network: points
